language: generic

jobs:
  include:
  # - os: linux
  #   python: 2.7
  #   env: TRAVIS_PYTHON_VERSION=2.7 TEST_WITH_XSPEC=false CONDA_UPLOAD=false
  # - os: osx
  #   python: 2.7
  #   env: TRAVIS_PYTHON_VERSION=2.7 TEST_WITH_XSPEC=false CONDA_UPLOAD=false
  - os: linux
    python: 2.7
    env: TRAVIS_PYTHON_VERSION=2.7 TEST_WITH_XSPEC=true CONDA_UPLOAD=true
  - os: osx
    python: 2.7
    env: TRAVIS_PYTHON_VERSION=2.7 TEST_WITH_XSPEC=true CONDA_UPLOAD=true
  # - os: linux
  #   python: 3.5
  #   env: TRAVIS_PYTHON_VERSION=3.5 TEST_WITH_XSPEC=false CONDA_UPLOAD=false
  # - os: osx
  #   python: 3.5
  #   env: TRAVIS_PYTHON_VERSION=3.5 TEST_WITH_XSPEC=false CONDA_UPLOAD=false
  # - os: linux
  #   python: 3.6
  #   env: TRAVIS_PYTHON_VERSION=3.6 TEST_WITH_XSPEC=false CONDA_UPLOAD=false
  # - os: osx
  #   python: 3.6
  #   env: TRAVIS_PYTHON_VERSION=3.6 TEST_WITH_XSPEC=false CONDA_UPLOAD=false
  # - os: linux
  #   python: 3.7
  #   env: TRAVIS_PYTHON_VERSION=3.7 TEST_WITH_XSPEC=false CONDA_UPLOAD=false
  # - os: osx
  #   python: 3.7
  #   env: TRAVIS_PYTHON_VERSION=3.7 TEST_WITH_XSPEC=false CONDA_UPLOAD=false
  # - os: linux
  #   python: 3.5
  #   env: TRAVIS_PYTHON_VERSION=3.5 TEST_WITH_XSPEC=true CONDA_UPLOAD=true
  # - os: osx
  #   python: 3.5
  #   env: TRAVIS_PYTHON_VERSION=3.5 TEST_WITH_XSPEC=true CONDA_UPLOAD=true
  # - os: linux
  #   python: 3.6
  #   env: TRAVIS_PYTHON_VERSION=3.6 TEST_WITH_XSPEC=true CONDA_UPLOAD=true
  # - os: osx
  #   python: 3.6
  #   env: TRAVIS_PYTHON_VERSION=3.6 TEST_WITH_XSPEC=true CONDA_UPLOAD=true
  - os: linux
    python: 3.7
    env: TRAVIS_PYTHON_VERSION=3.7 TEST_WITH_XSPEC=true CONDA_UPLOAD=true
  - os: osx
    python: 3.7
    env: TRAVIS_PYTHON_VERSION=3.7 TEST_WITH_XSPEC=true CONDA_UPLOAD=true

before_install:
- |
  if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then
    #docker pull condaforge/linux-anvil

    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    conda install -y conda-build
    conda config --add channels conda-forge
  else

    # Install Miniconda
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
    bash miniconda.sh -b -p $HOME/miniconda
    export PATH="$HOME/miniconda/bin:$PATH"
    conda install -y conda-build
    conda config --add channels conda-forge

  fi
  
script:
- chmod u+x ci/build_and_test.sh
- |
  while sleep 500; do
     echo "====[ $SECONDS seconds still running ]===="
  done &
- "./ci/build_and_test.sh"

deploy:
  provider: pypi
  user: __token__
  password:
    secure: 2I14ixrWgiOiE2ha9sai44mJC8stU9pB2sv/51AMIU6E1TK09RCzRd7Hk6KeuBk7bdF6+qnBcA8khicEkwamvxmtUre2RBOjO3PE9qBdHmPHfMF19fZWSxWHHBL76I6O212MkvzQWpmWEksPcLYf2wgeOv7wMNTzjFJjd39AQE+zZUpA38OOSjHn1FJe+sf/ru8f99vTu4tCEjiNvf3THbw3s22bEQcquhehXM+UB7ZNU4s1iGgMgJHHrIHhPF/1t67iddOeKbYFzkAtRaanNf5r2Z2m0w67Nx5hJSXxbfJN3RrWGj8/SdMj0IxT4gK88WzM5BY2fKhyvewRRP5ph7a/9EA3NsabhSKor6R5Q/pJQUJR7Ln1t0Sw3oziUmcLOYna6ijfBML1cJtn24jNR8mt73/h7Wj6iPnx8yTpKL1oUGKDQIjdEdsMGSiyTRPdTv6ynV67UybbENQtIoNNrGa0l2TguF3AV+FoZGlPy1uYaM3LZ/FKqMPsGRtxmzn8W8bldZXZnzYfMNS3VculTEZ5v3KoF9CbFvE5udEvB558yhB8PV3oR+oajpEGy9E1U6pskMOVpATG0s3ne7U83kgmRcT2ArfTzOWYv3MYZBNZm4vBlQLH37+KXO2rZoVVygoYVS6g1mCz9d8yWZdoo9zb+epNX57xAUz2ewZboyk=
  distributions: sdist
  skip_existing: true
  on:
    tags: true
