{% set name = "astromodels" %}

package:
  name: {{ name }}
  version: {{ os.environ.get('PKG_VERSION') }}

source:
#  git_url: https://github.com/threeml/{{ name }}.git
  path: ../../

requirements:
  build:
    - {{ compiler('c') }} # [linux]
    - {{ compiler('cxx') }} # [linux]
    - {{ compiler('fortran') }} # [linux]
    - krb5==1.14.6


  host:
    - python<=2.7.16 # [py2k]
    - python # [py3k]
    - setuptools
    - pip
    - numpy
    - pyyaml==3.13 
    - astropy
    #- scipy
    - numdifftools
    #- hdf5
    #- pytables
    - pandas>=0.23
    - future
    - krb5==1.14.6
    - numba
   
    - h5py

  run:
    - python
    - numpy
    - pyyaml==3.13
    - astropy
    #- scipy
    - numdifftools
    #- hdf5
    #- pytables
    - pandas>=0.23
    - dill
    - future
    - krb5==1.14.6
    - numba

    - h5py
    
build:
  script: python -m pip install --verbose --no-deps --ignore-installed .
  skip: true  # [win]
  #skip: true  # [py3k]

test:
  # Python imports
  imports:
    - astromodels
    - astromodels.core
    - astromodels.functions
    - astromodels.functions.dark_matter
    - astromodels.sources
    - astromodels.utils


#  commands:
#    - pytest -vv --pyargs {{ name }}

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.



about:
  home: https://github.com/threeml/astromodels
  license: UNKNOWN
  summary: 'Astromodels contains models to be used in likelihood or Bayesian analysis in astronomy'
  license_family: OTHER

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
